### ISSUE TITLE
Institution sectors should be as follows

### ISSUE THREAD

**Issue by NaduniRanasinghe** [moe-lk/sis#22]
[Updated Institutions.docx](https://github.com/moe-lk/sis/files/2802314/Updated.Institutions.docx)

**Comment by mohamednizar** [comment]
Add Institutions

1.Government Schools
1. National 
2. Provincial
3. Pirivena
4. Government Approved schools for Special Education

2.Private Schools

1. Government Aided
2. Government Non- Aided

3.International Schools

Institution provider should be an input text field
Institution - Classification should be removed, because all the institutions are academic

**Comment by NaduniRanasinghe** [comment]
@mohamednizar 
This is the updated format of Adding Institutes

Add Institutions

1.Government Schools

National
Provincial
Pirivena - 1. Moolika  2. Maha  3. Vidyatana
Government Approved schools for Special Education

2.Private Schools

Government Aided
Government Non- Aided

3.International Schools

**Institution provider should be an input text field
Institution - Classification should be removed, because all the institutions are academic**

There are 4 main categories of all the schools (Need a combo box or radio buttons)
**1AB
1C
Type 2
Type 3**

New field needs to be added

Technology Stream   - Yes or No 
If 'yes': (Radio Buttons)
         Engineering Technology
         Bio Systems Technology
         Both

**Comment by NaduniRanasinghe** [comment]
This can be configured manually after deploying the production environment
